### ISSUE TITLE
where is folder "cd /gym-torcs/ command"

### ISSUE THREAD

**Issue by lyokka** [imagry/Gym-Torcs-DQN#3]
Sorry I don't find folder "gym-torcs/command", and don't know how to implement this step of installation

2.2 install gym-torcs

    cd /gym-torcs/ command:
    SRC_DIR=proto DST_DIR=. CPP_DST_DIR=vtorcs-RL-color/src/drivers/scr_server/; protoc -I=$SRC_DIR --cpp_out=$CPP_DST_DIR --python_out=$DST_DIR $SRC_DIR/car_state.proto

--------------------------------------------------------------------------------------------------------------------------------

By the way, I also encounter installation problem 

        /home/ye/Desktop/gym_torcs/Gym-Torcs-DQN/vtorcs-RL-color/Make-default.mk:680: recipe for target 'subdirs' failed
        make[1]: *** [subdirs] Error 1
        make[1]: Leaving directory '/home/ye/Desktop/gym_torcs/Gym-Torcs-DQN/vtorcs-RL-color'
        Makefile:30: recipe for target 'restart' failed make: *** [restart] Error 2

**Comment by mantonios107** [comment]
Hi lyokka,

I encountered the same problem during the installation procedure.

I solved the first problem you mentioned by going in the folder where you unzip or clone the repository, that in your computer should be: 
/home/ye/Desktop/gym_torcs/Gym-Torcs-DQN/
where you can find the "proto" folder.

In addition I solved the second problem by copying all the *.png files from the original repository of [gym_torcs](https://github.com/ugo-nama-kun/gym_torcs) to the correct folders in the Gym-Torcs-DQN repository, before starting the installation procedure. This because in .gitignore of Gym-Torcs-DQN all the *.png files are excluded from git.

I hope this can help you.

**Comment by s271** [comment]
You should just make 2 commands:
cd /gym-torcs/
SRC_DIR=proto DST_DIR=. CPP_DST_DIR=vtorcs-RL-color/src/drivers/scr_server/; protoc -I=$SRC_DIR --cpp_out=$CPP_DST_DIR --python_out=$DST_DIR $SRC_DIR/car_state.proto

**Comment by lyokka** [comment]
Thanks, I finally installed in another way, really thank you

**Comment by AliBaheri** [comment]
Hi @lyokka 

How did you solve the second issue in the very first post of this tread?

**Comment by AliBaheri** [comment]
> Hi lyokka,
> 
> I encountered the same problem during the installation procedure.
> 
> I solved the first problem you mentioned by going in the folder where you unzip or clone the repository, that in your computer should be:
> /home/ye/Desktop/gym_torcs/Gym-Torcs-DQN/
> where you can find the "proto" folder.
> 
> In addition I solved the second problem by copying all the *.png files from the original repository of [gym_torcs](https://github.com/ugo-nama-kun/gym_torcs) to the correct folders in the Gym-Torcs-DQN repository, before starting the installation procedure. This because in .gitignore of Gym-Torcs-DQN all the *.png files are excluded from git.
> 
> I hope this can help you.

@lyokka Would you please provide some info how did you resolve the issue? Dose really copying all the *.png files from the original repository of gym_torcs to the correct folders in the Gym-Torcs-DQN repository solve the problem?

**Comment by marysavari** [comment]
@lyokka  and @AliBaheri  did you solve the second problem? Would you please share it if it is solved?
